# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            j.dytry.ch
tagline:          A blog about building games and learning tools, often at the same time.
url:              http://j.dytry.ch
paginate:         6
baseurl:          /
author:
  name:           Joe Dytrych
  url:            https://twitter.com/somehats
  email:          j@dytry.ch

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/somehats/j.dytry.ch
excerpt_separator: <!--more-->
